### PR TITLE
Week 2 PR 

### PR DESCRIPTION
**Pull request by glaracuente**

### CODE REVIEW

**Comment by gusostow** [comment]
What are the two instances for that are brought up by terraform?

**Comment by glaracuente** [comment]
There is one "captain" server brought up to run my CLI, alongside ansible. 

The 2 "resource_server" instances are supposed to represent 2 physical servers in a data center. The "captain" instance will turn these into a master node and worker node in a k8s cluster with the 'resource_pool create' command, but the code is not all connected for the full flow to work yet.

**Review by gusostow — CHANGES_REQUESTED** [review]
Nice progress so far.

Some requests:
- Not sure why `resource_pool_cli/resource_pool` doesn't have a `.py` file extension...
- You probably will want to structure your CLI as a pip installable package (https://python-packaging.readthedocs.io/en/latest/minimal.html) even though you plan to release it as a docker image.

I'm looking forward to figuring out some infrastructure integration tests for this with you.

**Comment by glaracuente** [comment]
thanks for the advice, I'll make these changes, and will definitely need some help figuring out tests

**Pull request merged**
